name: Metrics

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.WORKFLOW_GIT_ACCESS_TOKEN }}
          user: yml-blog
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/New_York
          config_order: code, base.header, base.activity+community, base.repositories, notable, stargazers, people, habits, activity, followup, languages, isocalendar, achievements
          plugin_achievements: yes
          plugin_activity: yes
          plugin_languages: yes
          plugin_stargazers: yes
          plugin_traffic: yes

      - name: Full-year calendar
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.isocalendar.fullyear.svg
          token: ${{ secrets.WORKFLOW_GIT_ACCESS_TOKEN }}
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
